- name: Create shared storage directory
  file:
    dest: "{{ item.dir }}"
    state: directory
  with_items: nfs_server_exports

- name: Configure /etc/exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: restart nfs
